### ISSUE TITLE
Mentor update information

### ISSUE THREAD

**Issue by Ni42** [corona-school/backend#97]
See corona-school/project-user/issues/63

Extend `PUT /user/:id putUser` (?)

**Comment by kevinbischof** [comment]
I noticed that in the function putPersonal the attribute email is not updated. Is it currently not possible for students and pupils to change their email address?
See https://github.com/corona-school/backend/blob/4a593c0e356af6ac4ee9985a745cebebac1feaa5/web/controllers/userController/index.ts#L483

**Comment by kevinbischof** [comment]
I actually got a problem with auth.ts 
https://github.com/corona-school/backend/blob/af5d541922b1fa1d4550791bb5888b0a372d4002/web/middleware/auth.ts#L69

The terminal log:
```
[2020-10-08T17:36:30.179] [INFO] default - DEV server listening on port 5000
mentor instanceof Mentor
Mentor {
  id: 1,
  createdAt: 2020-10-08T15:36:29.966Z,
  updatedAt: 2020-10-08T15:36:29.966Z,
  firstname: 'Aurelie',
  lastname: 'Streich',
  active: true,
  email: 'aurelie.streich@example.com',
  verification: null,
  verifiedAt: 2020-10-08T15:33:09.964Z,
  authToken: '0f402693e2cdf68868b35e7cc8b5d275693244c88bed69d68d795265c651cf29c1e8b8e269c7d19ec841867c5774ffe32da78b8c3c9501e898673527fc6256fc',
  authTokenUsed: true,
  authTokenSent: null,
  wix_id: '00000000-0000-0001-0001-1b4c4c526364',
  wix_creation_date: 2020-10-08T12:49:49.964Z,
  division: [ 'events', 'facebook' ],
  expertise: [ '"specialized expertise in subjects"' ],
  subjects: '[{"name":"Englisch","minGrade":1,"maxGrade":8},{"name":"Spanisch","minGrade":6,"maxGrade":10}]',
  teachingExperience: null,
  message: 'text',
  description: 'text',
  imageUrl: null
}
[2020-10-08T17:36:38.134] [DEBUG] default - QueryFailedError: invalid input value for enum mentor_expertise_enum: ""specialized expertise in subjects""
    at new QueryFailedError (/home/kbischof/IdeaProjects/corona-school/backend/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.callback (/home/kbischof/IdeaProjects/corona-school/backend/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:176:38)
    at Query.handleError (/home/kbischof/IdeaProjects/corona-school/backend/node_modules/pg/lib/query.js:146:19)
    at Connection.connectedErrorMessageHandler (/home/kbischof/IdeaProjects/corona-school/backend/node_modules/pg/lib/client.js:233:17)
    at Connection.emit (events.js:210:5)
    at /home/kbischof/IdeaProjects/corona-school/backend/node_modules/pg/lib/connection.js:109:10
    at Parser.parse (/home/kbischof/IdeaProjects/corona-school/backend/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/home/kbischof/IdeaProjects/corona-school/backend/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  message: 'invalid input value for enum mentor_expertise_enum: ""specialized expertise in subjects""',
  length: 138,
  name: 'QueryFailedError',
  severity: 'ERROR',
  code: '22P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'enum.c',
  line: '56',
  routine: 'enum_in',
  query: 'UPDATE "mentor" SET "authTokenUsed" = $2, "division" = $3, "expertise" = $4, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" IN ($1) RETURNING "updatedAt"',
  parameters: [
    1,
    1,
    [ 'events', 'facebook' ],
    [ '"specialized expertise in subjects"' ]
  ]
}
[2020-10-08T17:36:38.136] [ERROR] default - Error in auth check: invalid input value for enum mentor_expertise_enum: ""specialized expertise in subjects""

```

You can see that the attribute expertise is suddenly in double quotes: `  expertise: [ '"specialized expertise in subjects"' ],`
auth.ts actually does nothing on this attribute. Expertise is a enum analog to analogous to division and with division is everything ok.
There must be a problem in the process of getting the entity from db. There must be a transformation with expertise where it gets these double quotes, but I cant find it.

**Comment by geroembser** [comment]
> I noticed that in the function putPersonal the attribute email is not updated. Is it currently not possible for students and pupils to change their email address?
> See
> 
> https://github.com/corona-school/backend/blob/4a593c0e356af6ac4ee9985a745cebebac1feaa5/web/controllers/userController/index.ts#L483

Yes you‘re right. It shouldn’t be possible to change the email address at the moment. So once registered students and pupils shouldn’t have any option to change their email address.

**Comment by kevinbischof** [comment]
> > I noticed that in the function putPersonal the attribute email is not updated. Is it currently not possible for students and pupils to change their email address?
> > See
> > https://github.com/corona-school/backend/blob/4a593c0e356af6ac4ee9985a745cebebac1feaa5/web/controllers/userController/index.ts#L483
> 
> Yes you‘re right. It shouldn’t be possible to change the email address at the moment. So once registered students and pupils shouldn’t have any option to change their email address.

And mentors also shouldnt be able to change their email?

**Comment by geroembser** [comment]
> And mentors also shouldnt be able to change their email?

Exactly 👍 No user should be able to change their email, including the mentors.
